name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y meson libgtk-4-dev
    - name: meson setup
      run: meson setup build
    - name: build
      run: ninja -C build
