name: build release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y meson libgtk-4-dev
    - name: meson setup
      run: meson setup build
    - name: build
      run: ninja -C build
    - name: package
      run: |
        mv build/fastcrop fastcrop
        tar -czf fastcrop.tar.gz README.md COPYING fastcrop
    - uses: actions/github-script@v7
      env:
        RELEASE_ID: ${{github.event.release.id}}
      with:
        script: |
          const fs = require('fs');
          await github.rest.repos.uploadReleaseAsset({
            owner: context.repo.owner,
            repo: context.repo.repo,
            release_id: process.env.RELEASE_ID,
            name: "fastcrop_" + process.env.GITHUB_REF_NAME + "_linux64bit.tar.gz",
            data: fs.readFileSync("fastcrop.tar.gz")
          });
