name: build release

on:
  release:
    types: [published]

jobs:
  release-ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        apt-get update
        apt-get install -y meson libgtk-4-dev
    - name: meson setup
      run: meson setup build
    - name: build
      run: ninja -C build
    - name: upload-release
      uses: ./.github/actions/upload-release
      with:
        distro: "ubuntu_24.04"
  release-fedora:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    steps:
    - uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        dnf -y update
        dnf -y install meson gcc gtk4-devel ImageMagick-devel
    - name: meson setup
      run: meson setup build
    - name: build
      run: ninja -C build
    - name: upload-release
      uses: ./.github/actions/upload-release
      with:
        distro: "fedora-40"
